import type { IdentityTranslations } from '../../i18n/types/identity';

export const identity: IdentityTranslations = {
  identity: {
    activeLabel: "Active Label",
    autoGeneratedAddresses: "Auto Generated Addresses",
    imapOk: "Imap Ok",
    mailtmDescription: "Mailtm Description",
    noImapConfigNeeded: "No Imap Config Needed",
    perfectForOneTimeRegistrations: "Perfect For One Time Registrations",
    planLabel: "Plan Label",
    temporaryEmailService: "Temporary Email Service"
  }
};
