import type { IdentityTranslations } from '../../i18n/types/identity';

export const identity: IdentityTranslations = {
  identity: {
    activeLabel: "Активен",
    autoGeneratedAddresses: "Автогенерируемые адреса",
    imapOk: "IMAP OK",
    mailtmDescription: "Описание mail.tm",
    noImapConfigNeeded: "Настройка IMAP не требуется",
    perfectForOneTimeRegistrations: "Подходит для разовых регистраций",
    planLabel: "План",
    temporaryEmailService: "Временный email-сервис"
  }
};
