"""Scaffold a new service-plugin package (plan todo 19).

Generates a self-contained ``kind=service`` plugin directory:

    plugin.json          — v2 manifest template (contributions + storage)
    <pkg>/__init__.py    — package marker
    <pkg>/__main__.py    — RPC entry using ``autoreg.plugin.rpc.RpcPluginServer``
                           (with a vendored fallback for standalone operation)
    <pkg>/_vendor/       — vendored RpcPluginServer + plugin helpers (regenerated by dev-install)
    <pkg>/storage.py     — SQLite helper (WAL, migrate, CRUD)
    tests/test_plugin_protocol.py — protocol smoke test (raw-stdin harness)
    README.md            — dev loop quickstart

The generated package is unsigned.  Sign with::

    python -m stitch_plugin_tools sign <out_dir> --key <private.key>

then ``dev-install`` or ``publish``.
"""

from __future__ import annotations

import copy
import json
from datetime import date
from typing import TYPE_CHECKING, Any

from autoreg.plugin.manifest import MANIFEST_FILENAME, SCHEMA_ID_V2
from stitch_plugin_tools.scaffold_common import (
    _PLUGIN_ID_RE,
    CANONICAL_ENGINE,
    MARKER_PREFIX,
    SCAFFOLD_VERSION,
    _pkg_name,
    _validate_plugin_id,
    generated_by_field,
    marker_line,
)
from stitch_plugin_tools.scaffold_fallback import (
    _FALLBACK_ANCHOR_END,
    _FALLBACK_ANCHOR_START,
    _RPC_FALLBACK_BLOCK,
    _V2_FALLBACK_TEMPLATE,
)
from stitch_plugin_tools.scaffold_provider import scaffold_provider_plugin
from stitch_plugin_tools.scaffold_templates import (
    _MAIN_TEMPLATE,
    _README_TEMPLATE,
    _SERVICE_TEMPLATE,
    _STORAGE_TEMPLATE,
    _TEST_MAIN_TEMPLATE,
)

if TYPE_CHECKING:
    from pathlib import Path

__all__ = [
    "CANONICAL_ENGINE",
    "MARKER_PREFIX",
    "SCAFFOLD_VERSION",
    "_FALLBACK_ANCHOR_END",
    "_FALLBACK_ANCHOR_START",
    "_MAIN_TEMPLATE",
    "_PLUGIN_ID_RE",
    "_README_TEMPLATE",
    "_RPC_FALLBACK_BLOCK",
    "_SERVICE_TEMPLATE",
    "_STORAGE_TEMPLATE",
    "_TEST_MAIN_TEMPLATE",
    "_V2_FALLBACK_TEMPLATE",
    "_pkg_name",
    "_validate_plugin_id",
    "generated_by_field",
    "marker_line",
    "scaffold_provider_plugin",
    "scaffold_service_plugin",
]


def scaffold_service_plugin(
    out_dir: Path,
    *,
    plugin_id: str,
    name: str = "",
    author: str = "",
    version: str = "0.1.0",
    description: str = "",
    category: str = "productivity",
    status: str = "beta",
    icon: str = "🧩",
) -> Path:
    """Scaffold a service-plugin package into ``out_dir``.

    Creates ``plugin.json``, ``<pkg>/__init__.py``, ``<pkg>/__main__.py``,
    ``<pkg>/service.py``, ``<pkg>/storage.py``, ``tests/test_plugin_protocol.py``,
    and ``README.md``.  The directory is created if it does not exist;
    existing files are overwritten.

    The manifest is born with the marketplace metadata the official publish
    path requires (description/category/status) plus an icon, a one-entry
    features skeleton and a changelog seeded with the initial version dated
    today.

    Args:
        out_dir: Target directory for the package (created if absent).
        plugin_id: Plugin id (``[A-Za-z0-9_-]``).
        name: Human-readable name (defaults to ``plugin_id``).
        author: Optional author name (written to manifest extras).
        version: Semver version string (default ``"0.1.0"``).
        description: Short plain-text description (default: generated from
            the display name).
        category: Marketplace category (default ``"productivity"``).
        status: Marketplace status (default ``"beta"``).
        icon: Single emoji shown in the marketplace (default ``"🧩"``).

    Returns:
        The path to the assembled package directory (``out_dir``).
    """
    _validate_plugin_id(plugin_id)
    pkg_name = _pkg_name(plugin_id)
    display_name = name or plugin_id

    out_dir.mkdir(parents=True, exist_ok=True)
    pkg_dir = out_dir / pkg_name
    pkg_dir.mkdir(exist_ok=True)

    # i18n bundle is NESTED: flat keys like "{plugin_id}.title" never resolve in the FE walkBundle resolver.
    i18n_bundle = {
        plugin_id: {
            "title": display_name,
            "tab": display_name,
            "health_check": "Health Check",
            "echo": {
                "text": "Text to echo",
                "btn": "Echo",
            },
        }
    }
    manifest: dict[str, Any] = {
        "schema": SCHEMA_ID_V2,
        "id": plugin_id,
        "name": display_name,
        "version": version,
        "service": plugin_id,
        "kind": "service",
        "engine": dict(CANONICAL_ENGINE),
        "depends": [],
        "entry": {"module": pkg_name},
        "capabilities": [],
        "outputs": [],
        "signature": "",
        # Born with these: the official publish path refuses to ship without them.
        "description": description or f"{display_name} service plugin.",
        "category": category,
        "status": status,
        "icon": icon,
        "features": [
            {"title": f"{display_name} commands", "status": "beta"},
        ],
        "changelog": [
            {
                "version": version,
                "date": date.today().isoformat(),
                "changes": ["Initial release"],
            },
        ],
        "generated_by": generated_by_field(),
        "contributions": {
            "commands": [
                {"name": "health_check", "readonly": True},
                {"name": "echo", "readonly": True},
            ],
            "ui": {
                "kind": "declarative",
                "tabs": [
                    {
                        "id": plugin_id,
                        "label": f"{plugin_id}.tab",
                        "icon": "Plug",
                        "page": "main",
                    }
                ],
                "page": {
                    "title": f"{plugin_id}.title",
                    "nodes": [
                        {
                            "kind": "button",
                            "id": "health-check-btn",
                            "label": f"{plugin_id}.health_check",
                            "command": "health_check",
                            "variant": "primary",
                        },
                        {
                            "kind": "field",
                            "field": "text",
                            "id": "echo-field",
                            "label": f"{plugin_id}.echo.text",
                        },
                        {
                            "kind": "button",
                            "id": "echo-btn",
                            "label": f"{plugin_id}.echo.btn",
                            "command": "echo",
                            "params": {"text": ""},
                            "paramsFrom": {"text": "echo-field"},
                            "variant": "secondary",
                        },
                    ],
                },
            },
            "i18n": {
                "ru": copy.deepcopy(i18n_bundle),
                "en": copy.deepcopy(i18n_bundle),
            },
            "storage": {
                "sqlite": True,
                "migrations": "raw_sql",
            },
        },
    }
    if author:
        manifest["author"] = author

    (out_dir / MANIFEST_FILENAME).write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    (pkg_dir / "__init__.py").write_text(
        f'"""{display_name} service plugin."""\n',
        encoding="utf-8",
    )

    (pkg_dir / "__main__.py").write_text(
        _MAIN_TEMPLATE.format(
            pkg_name=pkg_name,
            plugin_id=plugin_id,
            scaffold_version=SCAFFOLD_VERSION,
        ),
        encoding="utf-8",
    )

    from stitch_plugin_tools.vendoring import vendor_all

    vendor_all(pkg_dir)

    (pkg_dir / "service.py").write_text(
        _SERVICE_TEMPLATE.format(scaffold_version=SCAFFOLD_VERSION),
        encoding="utf-8",
    )

    (pkg_dir / "storage.py").write_text(
        _STORAGE_TEMPLATE.format(scaffold_version=SCAFFOLD_VERSION),
        encoding="utf-8",
    )

    tests_dir = out_dir / "tests"
    tests_dir.mkdir(exist_ok=True)
    (tests_dir / "__init__.py").write_text(
        f'"""Test package for the {plugin_id} service plugin."""\n',
        encoding="utf-8",
    )
    (tests_dir / "test_plugin_protocol.py").write_text(
        _TEST_MAIN_TEMPLATE.format(
            plugin_id=plugin_id,
            pkg_name=pkg_name,
        ),
        encoding="utf-8",
    )

    (out_dir / "README.md").write_text(
        _README_TEMPLATE.format(
            plugin_id=plugin_id,
            pkg_name=pkg_name,
            name=display_name,
        ),
        encoding="utf-8",
    )

    return out_dir
