"""``stitch_plugin_tools typegen`` — typed param stubs from the manifest.

Reads ``contributions.commands[].params`` from ``plugin.json`` and writes
``<module>/_types.py`` (one ``TypedDict`` per command with a params
schema, ``Required``/``NotRequired`` via ``total=False``) plus
``<module>/ui-types.d.ts`` (one ``export interface`` per command).  Both
files carry the ``_generated_by: stitch_plugin_tools typegen v1`` marker;
existing files without the marker are refused (rc 2) so hand-written code
is never silently overwritten.  Output is deterministic — reruns are
byte-identical.
"""

from __future__ import annotations

import json
import re
import sys
from typing import TYPE_CHECKING, Any

from autoreg.plugin.manifest import (
    MANIFEST_FILENAME,
    ManifestValidationError,
    validate_manifest,
)

if TYPE_CHECKING:
    from pathlib import Path

_MARKER_STEM = "_generated_by: stitch_plugin_tools typegen v1"
_MARKER_PY = f"# {_MARKER_STEM}"
_MARKER_TS = f"// {_MARKER_STEM}"

_PY_TYPES = {
    "string": "str",
    "number": "int | float",
    "boolean": "bool",
    "object": "Dict[str, Any]",
    "array": "List[Any]",
}
_TS_TYPES = {
    "string": "string",
    "number": "number",
    "boolean": "boolean",
    "object": "Record<string, unknown>",
    "array": "unknown[]",
}


def _pascal(name: str) -> str:
    parts = [p for p in re.split(r"[^0-9a-zA-Z]+", name) if p]
    return "".join(p[:1].upper() + p[1:] for p in parts)


def _typing_imports(commands: list[tuple[str, dict[str, Any]]]) -> str:
    names = {"TypedDict"}
    for _name, params in commands:
        for spec in params.values():
            py_type = _PY_TYPES[spec["type"]]
            if py_type == "Dict[str, Any]":
                names.update({"Any", "Dict"})
            elif py_type == "List[Any]":
                names.update({"Any", "List"})
            if spec.get("required"):
                names.add("Required")
            else:
                names.add("NotRequired")
    return "from typing import " + ", ".join(sorted(names))


def _render_python(
    plugin_id: str, commands: list[tuple[str, dict[str, Any]]]
) -> str:
    lines = [
        f'"""Typed params for the {plugin_id} plugin commands.',
        "",
        "Generated by ``stitch_plugin_tools typegen`` from the manifest's",
        "``contributions.commands[].params`` schemas.  Rerun the command",
        "after editing plugin.json; delete this file to regenerate.",
        '"""',
        "",
        _MARKER_PY,
        "",
        "from __future__ import annotations",
        "",
        _typing_imports(commands),
        "",
        "",
    ]
    for name, params in commands:
        lines.append(f"class {_pascal(name)}Params(TypedDict, total=False):")
        for param_name, spec in params.items():
            wrapper = "Required" if spec.get("required") else "NotRequired"
            lines.append(f"    {param_name}: {wrapper}[{_PY_TYPES[spec['type']]}]")
        lines.append("")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def _render_ts(plugin_id: str, commands: list[tuple[str, dict[str, Any]]]) -> str:
    lines = [
        f"// Typed params for the {plugin_id} plugin commands.",
        "// Generated by stitch_plugin_tools typegen from plugin.json",
        "// (contributions.commands[].params).  Rerun after editing the",
        "// manifest; delete this file to regenerate.",
        "",
        _MARKER_TS,
        "",
    ]
    for name, params in commands:
        lines.append(f"export interface {_pascal(name)}Params {{")
        for param_name, spec in params.items():
            optional = "" if spec.get("required") else "?"
            lines.append(f"  {param_name}{optional}: {_TS_TYPES[spec['type']]};")
        lines.append("}")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def _commands_with_params(contributions: dict[str, Any]) -> list[tuple[str, dict[str, Any]]]:
    entries = contributions.get("commands")
    if not isinstance(entries, list):
        return []
    out: list[tuple[str, dict[str, Any]]] = []
    for entry in entries:
        if not isinstance(entry, dict):
            continue
        name = entry.get("name")
        params = entry.get("params")
        if isinstance(name, str) and name and isinstance(params, dict) and params:
            out.append((name, params))
    return out


def run_typegen(package_dir: Path) -> int:
    """Generate ``_types.py`` + ``ui-types.d.ts`` for one package dir."""
    if not package_dir.is_dir():
        print(f"error: package dir not found: {package_dir}", file=sys.stderr)
        return 2
    manifest_path = package_dir / MANIFEST_FILENAME
    if not manifest_path.is_file():
        print(f"error: manifest not found: {manifest_path}", file=sys.stderr)
        return 2
    try:
        raw = json.loads(manifest_path.read_text(encoding="utf-8"))
        manifest = validate_manifest(raw)
    except (OSError, ValueError, ManifestValidationError) as exc:
        print(f"error: invalid manifest: {exc}", file=sys.stderr)
        return 2

    from stitch_plugin_tools.upgrade import _package_module_dir

    module_dir = _package_module_dir(package_dir)
    if module_dir is None:
        print(
            f"error: no Python package dir (with __main__.py) found in "
            f"{package_dir}",
            file=sys.stderr,
        )
        return 2

    commands = _commands_with_params(manifest.contributions)
    if not commands:
        print("no commands with params schemas; nothing to generate")
        return 0

    for name, params in commands:
        class_name = _pascal(name)
        if not class_name or not class_name[0].isalpha():
            print(
                f"error: command {name!r} cannot map to a TypedDict name",
                file=sys.stderr,
            )
            return 2
        for param_name in params:
            if not param_name.isidentifier():
                print(
                    f"error: param name {param_name!r} of command {name!r} "
                    "is not a Python identifier",
                    file=sys.stderr,
                )
                return 2

    targets = (
        (module_dir / "_types.py", _render_python(manifest.id, commands)),
        (module_dir / "ui-types.d.ts", _render_ts(manifest.id, commands)),
    )
    for path, _content in targets:
        if path.exists() and _MARKER_STEM not in path.read_text(encoding="utf-8"):
            print(
                f"error: {path} has local edits; delete it to regenerate",
                file=sys.stderr,
            )
            return 2
    for path, content in targets:
        path.write_text(content, encoding="utf-8")
        print(f"generated {path}")
    return 0
