"""Upgrade authored service plugins to the current scaffold conventions.

``stitch_plugin_tools upgrade <package_dir>`` migrates a plugin package
generated by an older scaffold generation to the current one WITHOUT
clobbering author code:

- **Generation migration (v2→v3)**: replaces the inline
  ``RpcPluginServer`` fallback block in ``__main__.py`` with a 3-line
  try-import + creates ``_vendor/rpc_server.py`` from the canonical
  ``autoreg/plugin/rpc.py``.  Runs BEFORE region normalization.
- **Region normalization**: byte-compares ``_vendor/rpc_server.py``
  against canonical (swap on drift), updates ``_generated_by`` marker
  lines, and canonicalizes the generated manifest fields (``engine``,
  ``generated_by``).
- **Author regions are never touched** — handlers, service logic,
  storage schema, contributions, UI, i18n, README, extra files.

The command writes a unified diff preview to ``<package>/upgrade.diff``
first; nothing is modified until ``--apply`` is passed.

Version detection reads the ``_generated_by`` marker (first line after
the module docstring), the manifest ``generated_by`` extra, or (for
v2-era packages that predate the marker convention) the inline fallback
block pattern in ``__main__.py``.  Packages with none of these are
reported as legacy — manual migration per ``docs/plugin-authoring.md``.

The machinery is generic (version comparison + a generation-migration
phase + a region registry), so a future scaffold v4 adds its changes by
extending the registry.
"""

from __future__ import annotations

import difflib
import json
import re
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path

from autoreg.plugin.manifest import MANIFEST_FILENAME
from stitch_plugin_tools.scaffold import (
    _FALLBACK_ANCHOR_END,
    _FALLBACK_ANCHOR_START,
    _RPC_FALLBACK_BLOCK,
    CANONICAL_ENGINE,
    MARKER_PREFIX,
    SCAFFOLD_VERSION,
    generated_by_field,
    marker_line,
)
from stitch_plugin_tools.vendoring import canonical_rpc_server_text

UPGRADE_DIFF_FILENAME = "upgrade.diff"

# Marker: ``# _generated_by: stitch_plugin_tools scaffold v<N>[-<tag>]``.
# A prerelease tag (e.g. ``v2-alpha``) sorts BEFORE the release of the
# same number: v2-alpha < v2 < v3-alpha < v3.
_MARKER_RE = re.compile(
    rf"^{re.escape(MARKER_PREFIX)}(\d+)(?:-([0-9A-Za-z._]+))?[ \t]*$",
    re.MULTILINE,
)

_FALLBACK_START = "try:\n    from autoreg.plugin.rpc import RpcPluginServer"

# v2-era fallback block signature: the ``except ImportError`` branch
# imports ``threading`` and ``time`` inline (the v3 try-import does not).
# Used to detect v2-era packages that lack a ``_generated_by`` marker.
_V2_FALLBACK_SIGNATURE = "except ImportError:\n    import threading"

# The v3 try-import block that replaces the v2 inline fallback.
_V3_TRY_IMPORT = (
    "try:\n"
    "    from autoreg.plugin.rpc import RpcPluginServer\n"
    "except ImportError:\n"
    "    from ._vendor.rpc_server import RpcPluginServer"
)

# Content of _vendor/__init__.py (empty marker so _vendor is a subpackage).
_VENDOR_INIT_TEXT = (
    '"""Vendored RPC server — regenerated by stitch_plugin_tools."""\n'
)


def _version_key(major: int, prerelease: str | None) -> tuple[int, int, str]:
    """Sortable key: release of N beats any prerelease of N."""
    return (major, 0 if prerelease else 1, prerelease or "")


CURRENT_VERSION_KEY = _version_key(SCAFFOLD_VERSION, None)


def format_version(major: int, prerelease: str | None) -> str:
    """Human-readable scaffold version (``v2``, ``v2-alpha``)."""
    return f"v{major}" + (f"-{prerelease}" if prerelease else "")


# ── Detection ────────────────────────────────────────────────────────────


@dataclass
class DetectedVersion:
    """Scaffold generation a package was generated by (or None = legacy)."""

    major: int
    prerelease: str | None
    source: str  # "marker" | "manifest" | "fallback_block"

    @property
    def key(self) -> tuple[int, int, str]:
        return _version_key(self.major, self.prerelease)

    @property
    def label(self) -> str:
        return format_version(self.major, self.prerelease)


def _package_module_dir(package_dir: Path) -> Path | None:
    """Resolve the Python package dir (the dir holding ``__main__.py``).

    Prefers ``entry.module`` from the manifest; falls back to the single
    subdirectory containing ``__main__.py``.
    """
    manifest_path = package_dir / MANIFEST_FILENAME
    if manifest_path.is_file():
        try:
            raw = json.loads(manifest_path.read_text(encoding="utf-8"))
        except (ValueError, OSError):
            raw = None
        if isinstance(raw, dict):
            module = (raw.get("entry") or {}).get("module")
            if isinstance(module, str) and (package_dir / module).is_dir():
                return package_dir / module
    candidates = [
        d for d in package_dir.iterdir()
        if d.is_dir() and (d / "__main__.py").is_file()
    ]
    if len(candidates) == 1:
        return candidates[0]
    return None


def detect_scaffold_version(package_dir: Path) -> DetectedVersion | None:
    """Detect the scaffold generation of a package (None = legacy/unmarked).

    Reads the ``_generated_by`` marker from ``__main__.py`` (then
    ``service.py`` / ``storage.py``); falls back to the manifest
    ``generated_by`` extra; falls back to the v2-era inline fallback
    block pattern in ``__main__.py`` (for packages that predate the
    marker convention but carry the v2 fallback class).
    """
    module_dir = _package_module_dir(package_dir)
    if module_dir is not None:
        for name in ("__main__.py", "service.py", "storage.py"):
            path = module_dir / name
            if not path.is_file():
                continue
            text = path.read_bytes().decode("utf-8", errors="replace")
            match = _MARKER_RE.search(text.replace("\r\n", "\n"))
            if match:
                return DetectedVersion(
                    major=int(match.group(1)),
                    prerelease=match.group(2),
                    source="marker",
                )
    manifest_path = package_dir / MANIFEST_FILENAME
    if manifest_path.is_file():
        try:
            raw = json.loads(manifest_path.read_text(encoding="utf-8"))
        except (ValueError, OSError):
            raw = None
        if isinstance(raw, dict):
            generated = raw.get("generated_by")
            if (
                isinstance(generated, dict)
                and generated.get("tool") == "stitch_plugin_tools"
                and isinstance(generated.get("scaffold"), int)
            ):
                return DetectedVersion(
                    major=generated["scaffold"], prerelease=None, source="manifest"
                )
    # v2-era fallback: no marker, no generated_by, but __main__.py has
    # the inline fallback block pattern.  These are v2 packages that
    # predate the marker convention (the 7 repo plugins).
    if module_dir is not None:
        main_path = module_dir / "__main__.py"
        if main_path.is_file():
            text = main_path.read_bytes().decode("utf-8", errors="replace")
            text_lf = text.replace("\r\n", "\n")
            if _FALLBACK_START in text_lf and _V2_FALLBACK_SIGNATURE in text_lf:
                return DetectedVersion(
                    major=2, prerelease=None, source="fallback_block"
                )
    return None


# ── Region registry ──────────────────────────────────────────────────────
#
# Each region rewrites ONE canonical (tool-generated) slice of a file and
# leaves everything else byte-for-byte untouched.  A region callable
# receives the LF-normalized file text and returns ``(new_text, note)``;
# ``new_text is None`` means "region not found / nothing to do".


@dataclass
class RegionResult:
    """Outcome of one canonical region during an upgrade run."""

    region: str
    file: str
    changed: bool
    note: str = ""


def _swap_vendor(text: str) -> tuple[str | None, str]:
    """Byte-compare ``_vendor/rpc_server.py`` against the canonical text.

    Swaps on drift; returns None when already canonical.  The canonical
    text is extracted from ``autoreg/plugin/rpc.py`` at upgrade time.
    """
    canonical = canonical_rpc_server_text()
    if text.replace("\r\n", "\n") == canonical:
        return None, "vendor file already canonical"
    return canonical, "vendor file drifted — swapped to canonical"


def _marker_regex() -> re.Pattern[str]:
    return re.compile(
        rf"^{re.escape(MARKER_PREFIX)}\S+[ \t]*$", re.MULTILINE
    )


def _update_marker(text: str) -> tuple[str | None, str]:
    """Rewrite or insert the ``_generated_by`` marker line to the current version.

    When a marker exists, it is updated in place.  When no marker exists,
    one is inserted after the module docstring (the first triple-quoted
    string block) — this handles v2-era packages that predate the marker
    convention.
    """
    match = _marker_regex().search(text)
    current = marker_line()
    if match is not None:
        line = text[match.start() : match.end()]
        if line.rstrip("\n") == current:
            return None, "marker already current"
        return (
            text[: match.start()] + current + text[match.end() :],
            f"marker updated to {current!r}",
        )
    # No marker found — insert one after the module docstring.
    first_triple = text.find('"""')
    if first_triple < 0:
        return None, "no marker and no module docstring to insert after"
    closing_triple = text.find('"""', first_triple + 3)
    if closing_triple < 0:
        return None, "module docstring not closed"
    after_close = closing_triple + 3
    # Skip newlines after the closing """ to find the next non-blank line.
    pos = after_close
    while pos < len(text) and text[pos] == "\n":
        pos += 1
    # Insert: marker + blank line before the next non-blank line.
    # text[:pos] ends with the newlines after """, text[pos:] starts with
    # the next non-blank line (e.g. ``from __future__``).
    insertion = current + "\n\n"
    return (
        text[:pos] + insertion + text[pos:],
        f"marker inserted (was missing) at {current!r}",
    )


def _canonicalize_manifest(text: str) -> tuple[str | None, str]:
    """Rewrite only the generated manifest fields (engine, generated_by)."""
    try:
        raw = json.loads(text)
    except ValueError:
        return None, "manifest is not valid JSON"
    if not isinstance(raw, dict):
        return None, "manifest root is not an object"
    changed = False
    engine = raw.get("engine")
    if not isinstance(engine, dict) or engine != CANONICAL_ENGINE:
        raw["engine"] = dict(CANONICAL_ENGINE)
        changed = True
    generated = raw.get("generated_by")
    if generated != generated_by_field():
        raw["generated_by"] = generated_by_field()
        changed = True
    if not changed:
        return None, "engine/generated_by already canonical"
    return (
        json.dumps(raw, indent=2, ensure_ascii=False) + "\n",
        "manifest engine + generated_by updated",
    )


# Region registry: (region name, relative file, rewrite callable).
# File paths may use ``{module}`` — resolved to the package's module dir.
RegionSpec = tuple[str, str, Callable[[str], tuple[str | None, str]]]

REGION_REGISTRY: list[RegionSpec] = [
    ("vendor", "{module}/_vendor/rpc_server.py", _swap_vendor),
    ("marker", "{module}/__main__.py", _update_marker),
    ("marker", "{module}/service.py", _update_marker),
    ("marker", "{module}/storage.py", _update_marker),
    ("manifest", MANIFEST_FILENAME, _canonicalize_manifest),
]

# Author-owned regions the upgrade NEVER touches (summary output).
SKIPPED_AUTHOR_REGIONS = (
    "__main__.py handlers (everything outside the try-import + marker)",
    "service.py domain logic",
    "storage.py schema and helpers",
    "plugin.json contributions/ui/i18n/commands/signature",
    "README.md and any extra files",
)


# ── Generation migration (v2→v3) ─────────────────────────────────────────
#
# Runs BEFORE region normalization when detected < current.  Replaces the
# inline fallback block with the 3-line try-import and creates _vendor/.


def _replace_fallback_with_try_import(text: str) -> tuple[str | None, str]:
    """Replace the inline fallback block with the v3 3-line try-import.

    The region spans from the ``try:`` import guard to the end of the
    inline class; the next ``# ── `` section comment terminates it.
    Returns ``(new_text, note)`` or ``(None, note)`` when no block found.
    """
    start = text.find(_FALLBACK_START)
    if start < 0:
        return None, "fallback block start anchor not found"
    end = text.find("\n# ── ", start + len(_FALLBACK_START))
    if end < 0:
        return None, "fallback block end anchor (# ── section) not found"
    region = text[start:end]
    # Check that this is actually a v2-era block (has the inline class),
    # not already a v3 try-import (which is much shorter).
    if _V2_FALLBACK_SIGNATURE not in region:
        return None, "fallback block already at v3 (try-import only)"
    # Preserve the blank-line separator between the block and the next
    # section comment exactly as the author's file has it.
    separator = region[len(region.rstrip("\n")):]
    new_block = _V3_TRY_IMPORT + separator
    return text[:start] + new_block + text[end:], (
        "inline RpcPluginServer fallback replaced with v3 try-import"
    )


def _generation_migration(
    package_dir: Path,
    module_dir: Path,
    module_rel: str,
    originals: dict[str, str],
    updated: dict[str, str],
    results: list[RegionResult],
) -> None:
    """Run the v2→v3 generation migration (inline block → try-import + vendor).

    Modifies ``updated`` and ``results`` in place.  Reads ``__main__.py``
    into ``originals`` if not already present, applies the fallback
    replacement, and creates ``_vendor/rpc_server.py`` + ``__init__.py``.
    """
    main_rel = f"{module_rel}/__main__.py"
    main_path = package_dir / main_rel
    if main_rel not in originals:
        originals[main_rel] = _read_lf(main_path)
        updated[main_rel] = originals[main_rel]

    new_main, note = _replace_fallback_with_try_import(updated[main_rel])
    if new_main is not None:
        updated[main_rel] = new_main
        results.append(RegionResult(
            region="generation_migration", file=main_rel, changed=True, note=note,
        ))
    else:
        results.append(RegionResult(
            region="generation_migration", file=main_rel, changed=False, note=note,
        ))

    # Create _vendor/rpc_server.py (new file).
    vendor_rel = f"{module_rel}/_vendor/rpc_server.py"
    vendor_path = package_dir / vendor_rel
    canonical = canonical_rpc_server_text()
    if vendor_path.is_file():
        existing = _read_lf(vendor_path)
        if existing == canonical:
            results.append(RegionResult(
                region="generation_migration", file=vendor_rel, changed=False,
                note="vendor file already canonical",
            ))
        else:
            originals[vendor_rel] = existing
            updated[vendor_rel] = canonical
            results.append(RegionResult(
                region="generation_migration", file=vendor_rel, changed=True,
                note="vendor file drifted — refreshed to canonical",
            ))
    else:
        originals[vendor_rel] = ""
        updated[vendor_rel] = canonical
        results.append(RegionResult(
            region="generation_migration", file=vendor_rel, changed=True,
            note="vendor file created from canonical rpc.py",
        ))

    # Create _vendor/__init__.py (new file, empty marker).
    init_rel = f"{module_rel}/_vendor/__init__.py"
    init_path = package_dir / init_rel
    if not init_path.is_file():
        originals[init_rel] = ""
        updated[init_rel] = _VENDOR_INIT_TEXT
        results.append(RegionResult(
            region="generation_migration", file=init_rel, changed=True,
            note="vendor __init__.py created",
        ))


# ── Merge engine ─────────────────────────────────────────────────────────


@dataclass
class UpgradeReport:
    """Result of an upgrade run (preview or apply)."""

    package_dir: Path
    status: str  # legacy | newer | up-to-date | preview | applied | no-drift
    detected: DetectedVersion | None
    results: list[RegionResult] = field(default_factory=list)
    diff_path: Path | None = None
    message: str = ""

    @property
    def changed_any(self) -> bool:
        return any(r.changed for r in self.results)


def _read_lf(path: Path) -> str:
    return path.read_bytes().decode("utf-8").replace("\r\n", "\n")


def _write_preserve_eol(path: Path, lf_text: str, original: str) -> None:
    """Write LF text back with the file's original line-ending style."""
    if "\r\n" in original:
        lf_text = lf_text.replace("\n", "\r\n")
    path.write_bytes(lf_text.encode("utf-8"))


def upgrade_package(package_dir: Path, *, apply: bool = False) -> UpgradeReport:
    """Preview (default) or apply (``apply=True``) a scaffold upgrade.

    Always writes ``<package>/upgrade.diff`` before any modification when
    changes are pending; the diff file is removed after a successful apply.
    """
    package_dir = package_dir.resolve()
    detected = detect_scaffold_version(package_dir)

    if detected is None:
        return UpgradeReport(
            package_dir=package_dir,
            status="legacy",
            detected=None,
            message=(
                "legacy plugin, manual migration needed: no _generated_by "
                "marker, no manifest generated_by field, and no v2-era "
                "inline fallback block found (package predates scaffold v2)"
            ),
        )

    if detected.key > CURRENT_VERSION_KEY:
        return UpgradeReport(
            package_dir=package_dir,
            status="newer",
            detected=detected,
            message=(
                f"package was generated by scaffold {detected.label} — newer "
                f"than this tooling (v{SCAFFOLD_VERSION}); upgrade "
                "stitch_plugin_tools first"
            ),
        )

    # ── Module dir resolution ──────────────────────────────────────────
    module_dir = _package_module_dir(package_dir)
    module_rel = module_dir.name if module_dir is not None else None

    originals: dict[str, str] = {}
    updated: dict[str, str] = {}
    results: list[RegionResult] = []

    # ── Generation migration (v2→v3): runs when detected < current ────
    if detected.key < CURRENT_VERSION_KEY and module_dir is not None:
        _generation_migration(
            package_dir, module_dir, module_rel, originals, updated, results,
        )

    # ── Region normalization (runs for both v2→v3 and v3 drift) ──────
    for region_name, rel_template, rewrite in REGION_REGISTRY:
        rel = rel_template.format(module=module_rel) if module_rel else rel_template
        if "{module}" in rel:
            results.append(
                RegionResult(
                    region=region_name,
                    file=rel_template,
                    changed=False,
                    note="module directory not found",
                )
            )
            continue
        path = package_dir / rel
        # New files created by generation migration are already in updated.
        if not path.is_file() and rel in updated:
            # Vendor file was just created by generation migration —
            # check it against canonical (should be a no-op).
            new_text, note = rewrite(updated[rel])
            changed = new_text is not None
            if changed:
                updated[rel] = new_text  # type: ignore[assignment]
            results.append(RegionResult(
                region=region_name, file=rel, changed=changed, note=note,
            ))
            continue
        if not path.is_file():
            results.append(
                RegionResult(
                    region=region_name, file=rel, changed=False, note="file not found"
                )
            )
            continue
        if rel not in originals:
            originals[rel] = _read_lf(path)
            updated[rel] = originals[rel]
        new_text, note = rewrite(updated[rel])
        changed = new_text is not None
        if changed:
            updated[rel] = new_text  # type: ignore[assignment]
        results.append(RegionResult(region=region_name, file=rel, changed=changed, note=note))

    report = UpgradeReport(
        package_dir=package_dir, status="preview", detected=detected, results=results
    )

    if not report.changed_any:
        report.status = "no-drift"
        report.message = (
            f"package at scaffold {detected.label}: all canonical regions "
            "already match the current conventions — nothing to do"
        )
        return report

    # ── Diff preview (always written before any modification) ──────────
    diff_parts: list[str] = []
    for rel in sorted(originals):
        if originals[rel] == updated[rel]:
            continue
        diff_parts.extend(
            difflib.unified_diff(
                originals[rel].splitlines(),
                updated[rel].splitlines(),
                fromfile=f"a/{rel}",
                tofile=f"b/{rel}",
                lineterm="",
            )
        )
    diff_path = package_dir / UPGRADE_DIFF_FILENAME
    diff_path.write_text("\n".join(diff_parts) + "\n", encoding="utf-8")
    report.diff_path = diff_path

    if not apply:
        report.message = (
            f"preview written to {diff_path} — re-run with --apply to write "
            "the changes"
        )
        return report

    # ── Apply ──────────────────────────────────────────────────────────
    for rel, new_text in updated.items():
        if new_text == originals[rel]:
            continue
        path = package_dir / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        _write_preserve_eol(path, new_text, originals[rel])
    diff_path.unlink(missing_ok=True)
    report.diff_path = None
    report.status = "applied"
    report.message = (
        "upgrade applied; the manifest changed — re-sign the package "
        "before publish (python -m stitch_plugin_tools sign)"
    )
    return report
