"""Upgrade authored service plugins to the current scaffold conventions.

``stitch_plugin_tools upgrade <package_dir>`` migrates a plugin package
generated by an older scaffold generation to the current one WITHOUT
clobbering author code:

- **Canonical regions only** are rewritten — the inline
  ``RpcPluginServer`` fallback block in ``__main__.py`` (byte-exact
  wholesale swap), the ``_generated_by`` marker lines, and the generated
  manifest fields (``engine``, ``generated_by``).
- **Author regions are never touched** — handlers, service logic,
  storage schema, contributions, UI, i18n, README, extra files.

The command writes a unified diff preview to ``<package>/upgrade.diff``
first; nothing is modified until ``--apply`` is passed.

Version detection reads the ``_generated_by`` marker (first line after
the module docstring) or the manifest ``generated_by`` extra.  Packages
without either predate scaffold v2 (the first marked generation) and are
reported as legacy — manual migration per ``docs/plugin-authoring.md``.

The machinery is generic (version comparison + a region registry), so a
future scaffold v3 adds its changes by extending the registry.
"""

from __future__ import annotations

import difflib
import json
import re
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path

from autoreg.plugin.manifest import MANIFEST_FILENAME
from stitch_plugin_tools.scaffold import (
    _RPC_FALLBACK_BLOCK,
    CANONICAL_ENGINE,
    MARKER_PREFIX,
    SCAFFOLD_VERSION,
    generated_by_field,
    marker_line,
)

UPGRADE_DIFF_FILENAME = "upgrade.diff"

# Marker: ``# _generated_by: stitch_plugin_tools scaffold v<N>[-<tag>]``.
# A prerelease tag (e.g. ``v2-alpha``) sorts BEFORE the release of the
# same number: v2-alpha < v2 < v3-alpha < v3.
_MARKER_RE = re.compile(
    rf"^{re.escape(MARKER_PREFIX)}(\d+)(?:-([0-9A-Za-z._]+))?[ \t]*$",
    re.MULTILINE,
)

_FALLBACK_START = "try:\n    from autoreg.plugin.rpc import RpcPluginServer"


def _version_key(major: int, prerelease: str | None) -> tuple[int, int, str]:
    """Sortable key: release of N beats any prerelease of N."""
    return (major, 0 if prerelease else 1, prerelease or "")


CURRENT_VERSION_KEY = _version_key(SCAFFOLD_VERSION, None)


def format_version(major: int, prerelease: str | None) -> str:
    """Human-readable scaffold version (``v2``, ``v2-alpha``)."""
    return f"v{major}" + (f"-{prerelease}" if prerelease else "")


# ── Detection ────────────────────────────────────────────────────────────


@dataclass
class DetectedVersion:
    """Scaffold generation a package was generated by (or None = legacy)."""

    major: int
    prerelease: str | None
    source: str  # "marker" | "manifest"

    @property
    def key(self) -> tuple[int, int, str]:
        return _version_key(self.major, self.prerelease)

    @property
    def label(self) -> str:
        return format_version(self.major, self.prerelease)


def _package_module_dir(package_dir: Path) -> Path | None:
    """Resolve the Python package dir (the dir holding ``__main__.py``).

    Prefers ``entry.module`` from the manifest; falls back to the single
    subdirectory containing ``__main__.py``.
    """
    manifest_path = package_dir / MANIFEST_FILENAME
    if manifest_path.is_file():
        try:
            raw = json.loads(manifest_path.read_text(encoding="utf-8"))
        except (ValueError, OSError):
            raw = None
        if isinstance(raw, dict):
            module = (raw.get("entry") or {}).get("module")
            if isinstance(module, str) and (package_dir / module).is_dir():
                return package_dir / module
    candidates = [
        d for d in package_dir.iterdir()
        if d.is_dir() and (d / "__main__.py").is_file()
    ]
    if len(candidates) == 1:
        return candidates[0]
    return None


def detect_scaffold_version(package_dir: Path) -> DetectedVersion | None:
    """Detect the scaffold generation of a package (None = legacy/unmarked).

    Reads the ``_generated_by`` marker from ``__main__.py`` (then
    ``service.py`` / ``storage.py``); falls back to the manifest
    ``generated_by`` extra.
    """
    module_dir = _package_module_dir(package_dir)
    if module_dir is not None:
        for name in ("__main__.py", "service.py", "storage.py"):
            path = module_dir / name
            if not path.is_file():
                continue
            text = path.read_bytes().decode("utf-8", errors="replace")
            match = _MARKER_RE.search(text.replace("\r\n", "\n"))
            if match:
                return DetectedVersion(
                    major=int(match.group(1)),
                    prerelease=match.group(2),
                    source="marker",
                )
    manifest_path = package_dir / MANIFEST_FILENAME
    if manifest_path.is_file():
        try:
            raw = json.loads(manifest_path.read_text(encoding="utf-8"))
        except (ValueError, OSError):
            raw = None
        if isinstance(raw, dict):
            generated = raw.get("generated_by")
            if (
                isinstance(generated, dict)
                and generated.get("tool") == "stitch_plugin_tools"
                and isinstance(generated.get("scaffold"), int)
            ):
                return DetectedVersion(
                    major=generated["scaffold"], prerelease=None, source="manifest"
                )
    return None


# ── Region registry ──────────────────────────────────────────────────────
#
# Each region rewrites ONE canonical (tool-generated) slice of a file and
# leaves everything else byte-for-byte untouched.  A region callable
# receives the LF-normalized file text and returns ``(new_text, note)``;
# ``new_text is None`` means "region not found / nothing to do".


@dataclass
class RegionResult:
    """Outcome of one canonical region during an upgrade run."""

    region: str
    file: str
    changed: bool
    note: str = ""


def _swap_fallback_block(text: str) -> tuple[str | None, str]:
    """Wholesale-swap the inline RpcPluginServer fallback block.

    The region spans from the ``try:`` import guard to the end of the
    inline class; the next ``# ── `` section comment terminates it.
    """
    start = text.find(_FALLBACK_START)
    if start < 0:
        return None, "fallback block start anchor not found"
    end = text.find("\n# ── ", start + len(_FALLBACK_START))
    if end < 0:
        return None, "fallback block end anchor (# ── section) not found"
    region = text[start:end]
    core = region.rstrip("\n") + "\n"
    if core == _RPC_FALLBACK_BLOCK:
        return None, "fallback block already canonical"
    # Preserve the blank-line separator between the block and the next
    # section comment exactly as the author's file has it.
    separator = region[len(core) - 1:]
    return text[:start] + _RPC_FALLBACK_BLOCK + separator + text[end:], (
        "inline RpcPluginServer fallback swapped byte-exactly"
    )


def _marker_regex() -> re.Pattern[str]:
    return re.compile(
        rf"^{re.escape(MARKER_PREFIX)}\S+[ \t]*$", re.MULTILINE
    )


def _update_marker(text: str) -> tuple[str | None, str]:
    """Rewrite the ``_generated_by`` marker line to the current version."""
    match = _marker_regex().search(text)
    if match is None:
        return None, "no marker line found"
    line = text[match.start() : match.end()]
    current = marker_line()
    if line.rstrip("\n") == current:
        return None, "marker already current"
    return (
        text[: match.start()] + current + text[match.end() :],
        f"marker updated to {current!r}",
    )


def _canonicalize_manifest(text: str) -> tuple[str | None, str]:
    """Rewrite only the generated manifest fields (engine, generated_by)."""
    try:
        raw = json.loads(text)
    except ValueError:
        return None, "manifest is not valid JSON"
    if not isinstance(raw, dict):
        return None, "manifest root is not an object"
    changed = False
    engine = raw.get("engine")
    if not isinstance(engine, dict) or engine != CANONICAL_ENGINE:
        raw["engine"] = dict(CANONICAL_ENGINE)
        changed = True
    generated = raw.get("generated_by")
    if generated != generated_by_field():
        raw["generated_by"] = generated_by_field()
        changed = True
    if not changed:
        return None, "engine/generated_by already canonical"
    return (
        json.dumps(raw, indent=2, ensure_ascii=False) + "\n",
        "manifest engine + generated_by updated",
    )


# Region registry: (region name, relative file, rewrite callable).
# File paths may use ``{module}`` — resolved to the package's module dir.
RegionSpec = tuple[str, str, Callable[[str], tuple[str | None, str]]]

REGION_REGISTRY: list[RegionSpec] = [
    ("fallback_block", "{module}/__main__.py", _swap_fallback_block),
    ("marker", "{module}/__main__.py", _update_marker),
    ("marker", "{module}/service.py", _update_marker),
    ("marker", "{module}/storage.py", _update_marker),
    ("manifest", MANIFEST_FILENAME, _canonicalize_manifest),
]

# Author-owned regions the upgrade NEVER touches (summary output).
SKIPPED_AUTHOR_REGIONS = (
    "__main__.py handlers (everything outside the fallback block + marker)",
    "service.py domain logic",
    "storage.py schema and helpers",
    "plugin.json contributions/ui/i18n/commands/signature",
    "README.md and any extra files",
)


# ── Merge engine ─────────────────────────────────────────────────────────


@dataclass
class UpgradeReport:
    """Result of an upgrade run (preview or apply)."""

    package_dir: Path
    status: str  # legacy | newer | up-to-date | preview | applied | no-drift
    detected: DetectedVersion | None
    results: list[RegionResult] = field(default_factory=list)
    diff_path: Path | None = None
    message: str = ""

    @property
    def changed_any(self) -> bool:
        return any(r.changed for r in self.results)


def _read_lf(path: Path) -> str:
    return path.read_bytes().decode("utf-8").replace("\r\n", "\n")


def _write_preserve_eol(path: Path, lf_text: str, original: str) -> None:
    """Write LF text back with the file's original line-ending style."""
    if "\r\n" in original:
        lf_text = lf_text.replace("\n", "\r\n")
    path.write_bytes(lf_text.encode("utf-8"))


def upgrade_package(package_dir: Path, *, apply: bool = False) -> UpgradeReport:
    """Preview (default) or apply (``apply=True``) a scaffold upgrade.

    Always writes ``<package>/upgrade.diff`` before any modification when
    changes are pending; the diff file is removed after a successful apply.
    """
    package_dir = package_dir.resolve()
    detected = detect_scaffold_version(package_dir)

    if detected is None:
        return UpgradeReport(
            package_dir=package_dir,
            status="legacy",
            detected=None,
            message=(
                "legacy plugin, manual migration needed: no _generated_by "
                "marker or manifest generated_by field found (package "
                "predates scaffold v2)"
            ),
        )

    if detected.key > CURRENT_VERSION_KEY:
        return UpgradeReport(
            package_dir=package_dir,
            status="newer",
            detected=detected,
            message=(
                f"package was generated by scaffold {detected.label} — newer "
                f"than this tooling (v{SCAFFOLD_VERSION}); upgrade "
                "stitch_plugin_tools first"
            ),
        )

    if detected.key == CURRENT_VERSION_KEY:
        return UpgradeReport(
            package_dir=package_dir,
            status="up-to-date",
            detected=detected,
            message=(
                f"package already at scaffold {detected.label} — nothing to do"
            ),
        )

    # ── Older marked generation: structured merge of canonical regions ──
    module_dir = _package_module_dir(package_dir)
    module_rel = module_dir.name if module_dir is not None else None

    originals: dict[str, str] = {}
    updated: dict[str, str] = {}
    results: list[RegionResult] = []

    for region_name, rel_template, rewrite in REGION_REGISTRY:
        rel = rel_template.format(module=module_rel) if module_rel else rel_template
        if "{module}" in rel:
            results.append(
                RegionResult(
                    region=region_name,
                    file=rel_template,
                    changed=False,
                    note="module directory not found",
                )
            )
            continue
        path = package_dir / rel
        if not path.is_file():
            results.append(
                RegionResult(
                    region=region_name, file=rel, changed=False, note="file not found"
                )
            )
            continue
        if rel not in originals:
            originals[rel] = _read_lf(path)
            updated[rel] = originals[rel]
        new_text, note = rewrite(updated[rel])
        changed = new_text is not None
        if changed:
            updated[rel] = new_text  # type: ignore[assignment]
        results.append(RegionResult(region=region_name, file=rel, changed=changed, note=note))

    report = UpgradeReport(
        package_dir=package_dir, status="preview", detected=detected, results=results
    )

    if not report.changed_any:
        report.status = "no-drift"
        report.message = (
            f"package at scaffold {detected.label}: all canonical regions "
            "already match the current conventions — nothing to do"
        )
        return report

    # ── Diff preview (always written before any modification) ──────────
    diff_parts: list[str] = []
    for rel in sorted(originals):
        if originals[rel] == updated[rel]:
            continue
        diff_parts.extend(
            difflib.unified_diff(
                originals[rel].splitlines(),
                updated[rel].splitlines(),
                fromfile=f"a/{rel}",
                tofile=f"b/{rel}",
                lineterm="",
            )
        )
    diff_path = package_dir / UPGRADE_DIFF_FILENAME
    diff_path.write_text("\n".join(diff_parts) + "\n", encoding="utf-8")
    report.diff_path = diff_path

    if not apply:
        report.message = (
            f"preview written to {diff_path} — re-run with --apply to write "
            "the changes"
        )
        return report

    # ── Apply ──────────────────────────────────────────────────────────
    for rel, new_text in updated.items():
        if new_text == originals[rel]:
            continue
        _write_preserve_eol(package_dir / rel, new_text, originals[rel])
    diff_path.unlink(missing_ok=True)
    report.diff_path = None
    report.status = "applied"
    report.message = (
        "upgrade applied; the manifest changed — re-sign the package "
        "before publish (python -m stitch_plugin_tools sign)"
    )
    return report
