"""Region registry + v2→v3 generation migration for the upgrade pipeline.

Each registry region rewrites ONE canonical (tool-generated) slice of a
file; the generation migration replaces the inline ``RpcPluginServer``
fallback block with the v3 try-import and creates ``_vendor/``.  All names
are re-exported from :mod:`stitch_plugin_tools.upgrade`.
"""

from __future__ import annotations

import json
import re
from collections.abc import Callable
from dataclasses import dataclass
from typing import TYPE_CHECKING

from autoreg.plugin.manifest import MANIFEST_FILENAME
from stitch_plugin_tools.scaffold import (
    CANONICAL_ENGINE,
    MARKER_PREFIX,
    generated_by_field,
    marker_line,
)
from stitch_plugin_tools.upgrade_detect import (
    _V3_TRY_IMPORT,
    _find_fallback_try,
    _find_module_docstring,
    _is_v2_fallback,
    _line_start_offsets,
)
from stitch_plugin_tools.vendoring import canonical_rpc_server_text

if TYPE_CHECKING:
    from pathlib import Path

# Content of _vendor/__init__.py (empty marker so _vendor is a subpackage).
_VENDOR_INIT_TEXT = (
    '"""Vendored RPC server — regenerated by stitch_plugin_tools."""\n'
)

#: Posix suffix identifying the vendored RPC server within a module dir.
VENDOR_RPC_REL_SUFFIX = "/_vendor/rpc_server.py"

#: Backup written next to a drifted vendored file before it is swapped.
VENDOR_BACKUP_SUFFIX = ".pre-upgrade.bak"


# Each region rewrites ONE canonical slice, leaves the rest byte-identical; returns (new_text, note), None = not found.


@dataclass
class RegionResult:
    """Outcome of one canonical region during an upgrade run."""

    region: str
    file: str
    changed: bool
    note: str = ""


def _swap_vendor(text: str) -> tuple[str | None, str]:
    """Byte-compare ``_vendor/rpc_server.py`` against the canonical text.

    Swaps on drift; returns None when already canonical.  The canonical
    text is extracted from ``autoreg/plugin/rpc.py`` at upgrade time.
    """
    canonical = canonical_rpc_server_text()
    if text.replace("\r\n", "\n") == canonical:
        return None, "vendor file already canonical"
    return canonical, "vendor file drifted — swapped to canonical"


def _marker_regex() -> re.Pattern[str]:
    return re.compile(
        rf"^{re.escape(MARKER_PREFIX)}\d+(?:-[0-9A-Za-z._]+)?[ \t]*$",
        re.MULTILINE,
    )


def _update_marker(text: str) -> tuple[str | None, str]:
    """Rewrite or insert the ``_generated_by`` marker line to the current version.

    When a marker exists, it is updated in place.  When no marker exists,
    one is inserted after the module docstring — found via ``ast.parse``
    (``tree.body[0]`` ``Expr`` ``Constant`` str) rather than the
    first-triple-quote heuristic, so a non-docstring leading string literal
    (e.g. inside a comment or assignment) does not mislead the insertion
    point.
    """
    match = _marker_regex().search(text)
    current = marker_line()
    if match is not None:
        line = text[match.start() : match.end()]
        if line.rstrip("\n") == current:
            return None, "marker already current"
        return (
            text[: match.start()] + current + text[match.end() :],
            f"marker updated to {current!r}",
        )
    # No marker found — insert one after the module docstring (AST-based).
    doc_span = _find_module_docstring(text)
    if doc_span is None:
        return None, "no marker and no module docstring to insert after"
    _, after_close = doc_span
    # Skip newlines after the closing """ to find the next non-blank line.
    pos = after_close
    while pos < len(text) and text[pos] == "\n":
        pos += 1
    # Insert: marker + blank line before the next non-blank line.
    insertion = current + "\n\n"
    return (
        text[:pos] + insertion + text[pos:],
        f"marker inserted (was missing) at {current!r}",
    )


def _canonicalize_manifest(text: str) -> tuple[str | None, str]:
    """Rewrite only the generated manifest fields (engine, generated_by)."""
    try:
        raw = json.loads(text)
    except ValueError:
        return None, "manifest is not valid JSON"
    if not isinstance(raw, dict):
        return None, "manifest root is not an object"
    changed = False
    engine = raw.get("engine")
    if not isinstance(engine, dict) or engine != CANONICAL_ENGINE:
        raw["engine"] = dict(CANONICAL_ENGINE)
        changed = True
    generated = raw.get("generated_by")
    if generated != generated_by_field():
        raw["generated_by"] = generated_by_field()
        changed = True
    if not changed:
        return None, "engine/generated_by already canonical"
    return (
        json.dumps(raw, indent=2, ensure_ascii=False) + "\n",
        "manifest engine + generated_by updated",
    )


# Region registry: (name, relative file, rewrite callable); file paths may use {module} for the module dir.
RegionSpec = tuple[str, str, Callable[[str], tuple[str | None, str]]]

REGION_REGISTRY: list[RegionSpec] = [
    ("vendor", "{module}" + VENDOR_RPC_REL_SUFFIX, _swap_vendor),
    ("marker", "{module}/__main__.py", _update_marker),
    ("marker", "{module}/service.py", _update_marker),
    ("marker", "{module}/storage.py", _update_marker),
    ("manifest", MANIFEST_FILENAME, _canonicalize_manifest),
]

# Author-owned regions the upgrade NEVER touches (summary output).
SKIPPED_AUTHOR_REGIONS = (
    "__main__.py handlers (everything outside the try-import + marker)",
    "service.py domain logic",
    "storage.py schema and helpers",
    "plugin.json contributions/ui/i18n/commands/signature",
    "README.md and any extra files",
)


# Generation migration (v2→v3): runs before region normalization, replacing the inline fallback with the try-import.


def _replace_fallback_with_try_import(text: str) -> tuple[str | None, str]:
    """Replace the inline fallback block with the v3 3-line try-import.

    Uses ``ast.parse`` to find the top-level ``Try`` whose body imports
    ``RpcPluginServer`` from ``autoreg.plugin.rpc`` and whose handler
    catches ``ImportError``.  The block spans from that ``Try`` to the
    next top-level def/class after it.  The v3 try-import replaces the
    ``Try`` block; the trailing content (blank lines, section comments)
    between the ``Try`` and the next def/class is preserved.

    Returns ``(new_text, note)`` or ``(None, note)`` when no block found
    or the block is already at v3 (no inline class in the handler).
    """
    found = _find_fallback_try(text)
    if found is None:
        return None, "fallback block start anchor not found"
    start, end, try_node = found
    if not _is_v2_fallback(try_node):
        return None, "fallback block already at v3 (try-import only)"
    # Compute the offset of the line after the Try's last line.
    offsets = _line_start_offsets(text)
    try_end = (
        offsets[try_node.end_lineno]
        if try_node.end_lineno is not None and try_node.end_lineno < len(offsets)
        else len(text)
    )
    # Trailing content between the Try block and the next def/class (blank lines, comments) — preserved.
    trailing = text[try_end:end]
    # The v3 try-import string lacks the trailing \n the Try block's last line had — add it back.
    new_block = _V3_TRY_IMPORT + "\n" + trailing
    return text[:start] + new_block + text[end:], (
        "inline RpcPluginServer fallback replaced with v3 try-import"
    )


def _read_lf(path: Path) -> str:
    return path.read_bytes().decode("utf-8").replace("\r\n", "\n")


def _generation_migration(
    package_dir: Path,
    module_dir: Path,
    module_rel: str,
    originals: dict[str, str],
    updated: dict[str, str],
    results: list[RegionResult],
) -> None:
    """Run the v2→v3 generation migration (inline block → try-import + vendor).

    Modifies ``updated`` and ``results`` in place.  Reads ``__main__.py``
    into ``originals`` if not already present, applies the fallback
    replacement, and creates ``_vendor/rpc_server.py`` + ``__init__.py``.
    """
    main_rel = f"{module_rel}/__main__.py"
    main_path = package_dir / main_rel
    if main_rel not in originals:
        originals[main_rel] = _read_lf(main_path)
        updated[main_rel] = originals[main_rel]

    new_main, note = _replace_fallback_with_try_import(updated[main_rel])
    if new_main is not None:
        updated[main_rel] = new_main
        results.append(RegionResult(
            region="generation_migration", file=main_rel, changed=True, note=note,
        ))
    else:
        results.append(RegionResult(
            region="generation_migration", file=main_rel, changed=False, note=note,
        ))

    # Create _vendor/rpc_server.py (new file).
    vendor_rel = f"{module_rel}/_vendor/rpc_server.py"
    vendor_path = package_dir / vendor_rel
    canonical = canonical_rpc_server_text()
    if vendor_path.is_file():
        existing = _read_lf(vendor_path)
        if existing == canonical:
            results.append(RegionResult(
                region="generation_migration", file=vendor_rel, changed=False,
                note="vendor file already canonical",
            ))
        else:
            originals[vendor_rel] = existing
            updated[vendor_rel] = canonical
            results.append(RegionResult(
                region="generation_migration", file=vendor_rel, changed=True,
                note="vendor file drifted — refreshed to canonical",
            ))
    else:
        originals[vendor_rel] = ""
        updated[vendor_rel] = canonical
        results.append(RegionResult(
            region="generation_migration", file=vendor_rel, changed=True,
            note="vendor file created from canonical rpc.py",
        ))

    # Create _vendor/__init__.py (new file, empty marker).
    init_rel = f"{module_rel}/_vendor/__init__.py"
    init_path = package_dir / init_rel
    if not init_path.is_file():
        originals[init_rel] = ""
        updated[init_rel] = _VENDOR_INIT_TEXT
        results.append(RegionResult(
            region="generation_migration", file=init_rel, changed=True,
            note="vendor __init__.py created",
        ))
