// Generated by scripts/generate_provider_ids.py - do not edit

export const ProviderId = {
  KIRO: 'kiro',
  KIRO_V2: 'kiro_v2',
  WINDSURF: 'windsurf',
  TRAE: 'trae',
  GITHUB: 'github',
  BITBUCKET: 'bitbucket',
  AWS: 'aws',
  AWS_BUILDER_ID: 'aws_builder_id',
  OPENAI: 'openai',
  COPILOT: 'copilot',
  CLAUDE: 'claude',
  ANTHROPIC: 'anthropic',
  GEMINI: 'gemini',
  ANTIGRAVITY: 'antigravity',
  ZAI: 'zai',
  FIREWORKS: 'fireworks',
  QODER: 'qoder',
  V0_APP: 'v0_app',
} as const;

export type ProviderId = (typeof ProviderId)[keyof typeof ProviderId];

export type ProviderCategory = 'ide' | 'git' | 'cloud' | 'ai';

export interface ProviderMeta {
  id: ProviderId;
  displayName: string;
  category: ProviderCategory;
  hasAutoreg: boolean;
  isAiProxy: boolean;
  aliases?: readonly ProviderId[];
  minEngineApi: number;
}

export const PROVIDER_META: Record<ProviderId, ProviderMeta> = {
  [ProviderId.KIRO]: {
    id: ProviderId.KIRO,
    displayName: 'Kiro',
    category: 'ide',
    hasAutoreg: true,
    isAiProxy: true,
    minEngineApi: 1,
  },
  [ProviderId.KIRO_V2]: {
    id: ProviderId.KIRO_V2,
    displayName: 'Kiro v2',
    category: 'ide',
    hasAutoreg: true,
    isAiProxy: true,
    minEngineApi: 1,
  },
  [ProviderId.WINDSURF]: {
    id: ProviderId.WINDSURF,
    displayName: 'Windsurf',
    category: 'ide',
    hasAutoreg: true,
    isAiProxy: true,
    minEngineApi: 1,
  },
  [ProviderId.TRAE]: {
    id: ProviderId.TRAE,
    displayName: 'Trae',
    category: 'ide',
    hasAutoreg: true,
    isAiProxy: false,
    minEngineApi: 1,
  },
  [ProviderId.GITHUB]: {
    id: ProviderId.GITHUB,
    displayName: 'GitHub',
    category: 'git',
    hasAutoreg: false,
    isAiProxy: false,
    minEngineApi: 1,
  },
  [ProviderId.BITBUCKET]: {
    id: ProviderId.BITBUCKET,
    displayName: 'Bitbucket',
    category: 'git',
    hasAutoreg: false,
    isAiProxy: false,
    minEngineApi: 1,
  },
  [ProviderId.AWS]: {
    id: ProviderId.AWS,
    displayName: 'AWS',
    category: 'cloud',
    hasAutoreg: false,
    isAiProxy: false,
    aliases: [ProviderId.AWS_BUILDER_ID],
    minEngineApi: 1,
  },
  [ProviderId.AWS_BUILDER_ID]: {
    id: ProviderId.AWS_BUILDER_ID,
    displayName: 'AWS Builder ID',
    category: 'cloud',
    hasAutoreg: false,
    isAiProxy: false,
    aliases: [ProviderId.AWS],
    minEngineApi: 1,
  },
  [ProviderId.OPENAI]: {
    id: ProviderId.OPENAI,
    displayName: 'OpenAI',
    category: 'ai',
    hasAutoreg: false,
    isAiProxy: true,
    minEngineApi: 1,
  },
  [ProviderId.COPILOT]: {
    id: ProviderId.COPILOT,
    displayName: 'Copilot',
    category: 'ai',
    hasAutoreg: false,
    isAiProxy: true,
    minEngineApi: 1,
  },
  [ProviderId.CLAUDE]: {
    id: ProviderId.CLAUDE,
    displayName: 'Claude',
    category: 'ai',
    hasAutoreg: false,
    isAiProxy: true,
    minEngineApi: 1,
  },
  [ProviderId.ANTHROPIC]: {
    id: ProviderId.ANTHROPIC,
    displayName: 'Anthropic',
    category: 'ai',
    hasAutoreg: false,
    isAiProxy: true,
    minEngineApi: 1,
  },
  [ProviderId.GEMINI]: {
    id: ProviderId.GEMINI,
    displayName: 'Gemini',
    category: 'ai',
    hasAutoreg: false,
    isAiProxy: true,
    minEngineApi: 1,
  },
  [ProviderId.ANTIGRAVITY]: {
    id: ProviderId.ANTIGRAVITY,
    displayName: 'Antigravity',
    category: 'ai',
    hasAutoreg: false,
    isAiProxy: true,
    minEngineApi: 1,
  },
  [ProviderId.ZAI]: {
    id: ProviderId.ZAI,
    displayName: 'Z.AI',
    category: 'ai',
    hasAutoreg: false,
    isAiProxy: true,
    minEngineApi: 1,
  },
  [ProviderId.FIREWORKS]: {
    id: ProviderId.FIREWORKS,
    displayName: 'Fireworks',
    category: 'ai',
    hasAutoreg: true,
    isAiProxy: true,
    minEngineApi: 1,
  },
  [ProviderId.QODER]: {
    id: ProviderId.QODER,
    displayName: 'Qoder',
    category: 'ide',
    hasAutoreg: true,
    isAiProxy: false,
    minEngineApi: 1,
  },
  [ProviderId.V0_APP]: {
    id: ProviderId.V0_APP,
    displayName: 'v0.dev',
    category: 'ai',
    hasAutoreg: true,
    isAiProxy: false,
    minEngineApi: 1,
  },
};

export const ALL_PROVIDER_IDS = Object.values(ProviderId) as ProviderId[];

export const AUTOREG_PROVIDERS = ALL_PROVIDER_IDS.filter(id => PROVIDER_META[id].hasAutoreg);

export const AI_PROXY_PROVIDERS = ALL_PROVIDER_IDS.filter(id => PROVIDER_META[id].isAiProxy);

export const PROVIDERS_BY_CATEGORY: Record<ProviderCategory, ProviderId[]> = {
  ide: ALL_PROVIDER_IDS.filter(id => PROVIDER_META[id].category === 'ide'),
  git: ALL_PROVIDER_IDS.filter(id => PROVIDER_META[id].category === 'git'),
  cloud: ALL_PROVIDER_IDS.filter(id => PROVIDER_META[id].category === 'cloud'),
  ai: ALL_PROVIDER_IDS.filter(id => PROVIDER_META[id].category === 'ai'),
};

export function isValidProviderId(id: string): id is ProviderId {
  return (ALL_PROVIDER_IDS as readonly string[]).includes(id);
}
