/**
 * Email Generation Service
 * Handles email generation logic for different strategies (Gmail, custom domain, alias services)
 */

import { getNextCounter } from '../../../lib/backend';
import { RANDOM_NAMES } from '../../../constants/registration';
import type { ProviderName } from '../../../types/ui';
import type { IMAPConfig } from '../../../stores/registration/types';

export interface EmailGenerationOptions {
  provider: ProviderName;
  imapConfig: IMAPConfig;
  emailPattern: string;
  emailCustomPrefix?: string; // actual template when emailPattern === 'custom_prefix'
  emailDomain: string;
}

export interface EmailGenerationResult {
  email: string | null;
  strategy: 'gmail' | 'addyio' | '33mail' | 'mailtm' | 'icloud_pool' | 'custom' | 'cf-to-imap';
  shouldGenerateInPython: boolean;
}

/**
 * Generate email address based on configured strategy
 * Returns null if email should be generated by Python (for alias services)
 */
export async function generateEmail(
  options: EmailGenerationOptions
): Promise<EmailGenerationResult> {
  const { provider, imapConfig, emailPattern, emailCustomPrefix, emailDomain } = options;

  // If addy.io, 33mail, Mail.tm, or iCloud pool is enabled, let Python generate the email
  if (imapConfig.addyioEnabled) {
    return {
      email: null,
      strategy: 'addyio',
      shouldGenerateInPython: true,
    };
  }

  if (imapConfig.thirtyThreeMailEnabled) {
    return {
      email: null,
      strategy: '33mail',
      shouldGenerateInPython: true,
    };
  }

  if (imapConfig.mailtmEnabled) {
    return {
      email: null,
      strategy: 'mailtm',
      shouldGenerateInPython: true,
    };
  }

  if (imapConfig.icloudEnabled) {
    return {
      email: null,
      strategy: 'icloud_pool',
      shouldGenerateInPython: true,
    };
  }

  // Gmail strategy
  if (imapConfig.strategy === 'gmail') {
    const email = await generateGmailEmail(provider, imapConfig);
    return {
      email,
      strategy: 'gmail',
      shouldGenerateInPython: false,
    };
  }

  // Custom domain / CF-to-IMAP strategy — resolve actual template
  // emailPattern is an enum key (e.g. 'custom_prefix'), emailCustomPrefix is the real template
  const resolvedPattern =
    emailPattern === 'custom_prefix' && emailCustomPrefix
      ? emailCustomPrefix
      : emailPattern;

  const email = await generateCustomEmail(provider, resolvedPattern, emailDomain);
  return {
    email,
    strategy: imapConfig.strategy === 'cf-to-imap' ? 'cf-to-imap' : 'custom',
    shouldGenerateInPython: false,
  };
}

/**
 * Generate Gmail email with plus addressing
 */
async function generateGmailEmail(provider: ProviderName, imapConfig: IMAPConfig): Promise<string> {
  const base = imapConfig.gmailBase.replace('@gmail.com', '');
  let alias = imapConfig.gmailAlias || 'alias';
  const timestamp = Date.now();

  // Replace {counter} first if present
  if (alias.includes('{counter}')) {
    const counter = await getNextCounter({
      provider,
      strategy: 'gmail',
    });
    alias = alias.replace(/\{counter\}/gi, counter.toString());
  }

  // Replace other placeholders
  alias = alias.replace(/\{rnd\}/gi, Math.random().toString(36).substring(2, 6));
  alias = alias.replace(/\{time\}/gi, timestamp.toString().slice(-6));
  alias = alias.replace(
    /\{name\}/gi,
    RANDOM_NAMES[Math.floor(Math.random() * RANDOM_NAMES.length)]
  );

  return `${base}+${alias}@gmail.com`;
}

/**
 * Generate custom domain email
 */
async function generateCustomEmail(
  provider: ProviderName,
  emailPattern: string,
  emailDomain: string
): Promise<string> {
  let pattern = String(emailPattern);
  const timestamp = Date.now();

  // Replace {counter} first if present
  if (pattern.includes('{counter}')) {
    const counter = await getNextCounter({
      provider,
      strategy: 'custom',
    });
    pattern = pattern.replace(/\{counter\}/gi, counter.toString());
  }

  // Replace other placeholders
  pattern = pattern.replace(/\{rnd\}/gi, Math.random().toString(36).substring(2, 6));
  pattern = pattern.replace(/\{time\}/gi, timestamp.toString().slice(-6));
  pattern = pattern.replace(
    /\{name\}/gi,
    RANDOM_NAMES[Math.floor(Math.random() * RANDOM_NAMES.length)]
  );

  return `${pattern}@${emailDomain}`;
}
