/**
 * Registration Runner Service
 * Handles registration execution logic, progress tracking, and error handling
 */

import {
  startWindsurfAutoreg,
  startPythonAutoreg,
  startTraeAutoreg,
  startGithubAutoreg,
  startOpenAIAutoreg,
  startRegistrationV2,
  addAccount,
  listAccounts,
  stopRegistration,
} from '../../../lib/tauri';
import { generateEmail } from './emailGenerator';
import { DEFAULT_IMAP_PORT } from '../../../constants/registration';
import type { ProviderName } from '../../../types';
import type { RegistrationConfig } from '../../../stores/registration/types';
import type {
  PythonAutoregResult,
  WindsurfAutoregResult,
  TraeAutoregResult,
  GithubAutoregResult,
} from '../../../types/generated';
import type { OpenAIAutoregResult } from '../../../types';

// Timeout for each registration attempt (5 minutes)
const REGISTRATION_TIMEOUT_MS = 5 * 60 * 1000;

export type LogLevel = 'info' | 'error' | 'success' | 'warn' | 'debug';
export type RegistrationStatus = 'pending' | 'running' | 'completed' | 'failed';

export interface RegistrationOptions {
  config: RegistrationConfig;
  emailDomain: string;
  useRegistrationV2: boolean;
  onLog: (level: LogLevel, message: string) => void;
  onHistoryEntry: (entry: {
    provider: ProviderName;
    email: string;
    status: RegistrationStatus;
  }) => void;
  onCancelled: () => boolean; // Returns true if cancelled
}

export interface RegistrationSummary {
  successCount: number;
  skipCount: number;
  failCount: number;
}

/**
 * Run registration for multiple accounts
 */
export async function runRegistration(options: RegistrationOptions): Promise<RegistrationSummary> {
  const { config, emailDomain, useRegistrationV2, onLog, onHistoryEntry, onCancelled } = options;

  const totalCount = config.count || 1;
  let successCount = 0;
  let skipCount = 0;
  let failCount = 0;

  // Determine IMAP credentials based on strategy (once, outside loop)
  const { imapServer, imapUser, imapPassword } = getIMAPCredentials(config);

  // Debug log IMAP config (without password)
  onLog(
    'debug',
    `IMAP config: server=${imapServer}, user=${imapUser}, password=${imapPassword ? '***set***' : '***empty***'}`
  );

  try {
    // Loop for multiple account registration
    for (let i = 0; i < totalCount; i++) {
      // Check if cancelled
      if (onCancelled()) {
        onLog('warn', `Registration cancelled by user at account ${i + 1}/${totalCount}`);
        break;
      }

      try {
        // Use Registration V2 for AWS/Kiro if enabled
        if (useRegistrationV2 && config.provider === 'aws') {
          const result = await runRegistrationV2(i, totalCount, onLog);
          if (result.success && result.email) {
            successCount++;
            onLog('success', `[${i + 1}/${totalCount}] Account created: ${result.email}`);
            onHistoryEntry({
              provider: config.provider,
              email: result.email,
              status: 'completed',
            });
          } else {
            failCount++;
            onLog(
              'error',
              `[${i + 1}/${totalCount}] Registration failed: ${result.error || 'Unknown error'}`
            );
          }

          // Delay between registrations
          if (i < totalCount - 1) {
            await delay(config.advanced.delayBetweenAccounts * 1000);
          }
          continue;
        }

        // Generate email
        const emailResult = await generateEmail({
          provider: config.provider,
          imapConfig: config.imap,
          emailPattern: config.patterns.emailPattern,
          emailDomain,
        });

        const { email, strategy, shouldGenerateInPython } = emailResult;

        if (shouldGenerateInPython) {
          const serviceName =
            strategy === 'addyio' ? 'addy.io' : strategy === '33mail' ? '33mail' : 'Mail.tm';
          onLog('info', `[${i + 1}/${totalCount}] Using ${serviceName} for email generation...`);
        }

        // Check if account already exists (skip if email will be generated by Python)
        if (email) {
          const existingAccounts = await listAccounts({ provider: config.provider });
          const accountExists = existingAccounts.some(
            acc => acc.email.toLowerCase() === email.toLowerCase()
          );

          if (accountExists) {
            skipCount++;
            onLog(
              'warn',
              `[${i + 1}/${totalCount}] Account ${email} already exists in database, skipping`
            );
            continue;
          }
        }

        onLog(
          'info',
          `[${i + 1}/${totalCount}] Registering ${email || '(email will be generated)'}...`
        );

        // Run provider-specific registration
        const result = await runProviderRegistration({
          provider: config.provider,
          email,
          config,
          imapServer,
          imapUser,
          imapPassword,
        });

        // Process result
        const processResult = await processRegistrationResult({
          result,
          provider: config.provider,
          index: i,
          totalCount,
          onLog,
          onHistoryEntry,
        });

        if (processResult === 'success') {
          successCount++;
        } else if (processResult === 'skip') {
          skipCount++;
        } else {
          failCount++;
        }

        // Delay between registrations
        if (i < totalCount - 1) {
          onLog(
            'debug',
            `Waiting ${config.advanced.delayBetweenAccounts}s before next registration...`
          );
          await delay(config.advanced.delayBetweenAccounts * 1000);
        }
      } catch (error) {
        failCount++;
        const errorMsg = String(error);
        if (errorMsg.includes('timed out')) {
          onLog(
            'error',
            `[${i + 1}/${totalCount}] ${errorMsg} - attempting to stop process and continue...`
          );
          // Try to stop the hung process
          try {
            await stopRegistration();
          } catch {
            // Ignore stop errors
          }
        } else {
          onLog('error', `[${i + 1}/${totalCount}] Error: ${errorMsg}`);
        }
      }

      // Log progress after each iteration
      onLog(
        'debug',
        `Completed ${i + 1}/${totalCount} registrations (success: ${successCount}, skip: ${skipCount}, fail: ${failCount})`
      );
    }
  } catch (error) {
    onLog('error', `Fatal error: ${String(error)}`);
    throw error;
  }

  return { successCount, skipCount, failCount };
}

/**
 * Get IMAP credentials based on strategy
 */
function getIMAPCredentials(config: RegistrationConfig): {
  imapServer: string;
  imapUser: string;
  imapPassword: string;
} {
  const imapServer = config.imap.strategy === 'gmail' ? 'imap.gmail.com' : config.imap.server;

  // For Gmail, ensure gmailBase has @gmail.com suffix
  let imapUser = config.imap.strategy === 'gmail' ? config.imap.gmailBase : config.imap.email;
  if (config.imap.strategy === 'gmail' && imapUser && !imapUser.includes('@')) {
    imapUser = `${imapUser}@gmail.com`;
  }

  const imapPassword =
    config.imap.strategy === 'gmail'
      ? config.imap.gmailAppPassword
      : config.imap.password || '********';

  return { imapServer, imapUser, imapPassword };
}

/**
 * Run Registration V2 (Rust-based flow)
 */
async function runRegistrationV2(
  index: number,
  totalCount: number,
  onLog: (level: LogLevel, message: string) => void
): Promise<{ success: boolean; email?: string; error?: string }> {
  onLog('info', `[${index + 1}/${totalCount}] Using Registration V2 (Rust-based flow)...`);

  try {
    const result = await withTimeout(
      startRegistrationV2({
        email: null,
        name: null,
        password: null,
      }),
      REGISTRATION_TIMEOUT_MS,
      `Registration timed out after ${REGISTRATION_TIMEOUT_MS / 60000} minutes`
    );

    return result;
  } catch (error) {
    return {
      success: false,
      error: String(error),
    };
  }
}

/**
 * Run provider-specific registration
 */
async function runProviderRegistration(params: {
  provider: ProviderName;
  email: string | null;
  config: RegistrationConfig;
  imapServer: string;
  imapUser: string;
  imapPassword: string;
}): Promise<
  | PythonAutoregResult
  | WindsurfAutoregResult
  | TraeAutoregResult
  | GithubAutoregResult
  | OpenAIAutoregResult
> {
  const { provider, email, config, imapServer, imapUser, imapPassword } = params;

  if (provider === 'windsurf') {
    return await withTimeout(
      startWindsurfAutoreg({
        email,
        password: null,
        name: null,
        headless: false,
        loginOnly: false,
        proxyUrl: config.proxy.enabled ? config.proxy.url : null,
        imapServer,
        imapPort: config.imap.port || DEFAULT_IMAP_PORT,
        imapUser,
        imapPassword,
        emailPattern: config.patterns.emailPattern,
        namePattern: config.patterns.namePattern,
        nameCustomFirst: config.patterns.nameCustomFirst,
        nameCustomLast: config.patterns.nameCustomLast,
        addyioEnabled: config.imap.addyioEnabled ?? null,
        addyioApiToken: config.imap.addyioApiToken ?? null,
        addyioDomain: config.imap.addyioDomain ?? null,
        addyioAliasFormat: config.imap.addyioAliasFormat ?? null,
        addyioAutoDelete: config.imap.addyioAutoDelete ?? null,
        thirtyThreeMailEnabled: config.imap.thirtyThreeMailEnabled ?? null,
        thirtyThreeMailUsername: config.imap.thirtyThreeMailUsername ?? null,
        thirtyThreeMailDomain: config.imap.thirtyThreeMailDomain ?? null,
        mailtmEnabled: config.imap.mailtmEnabled ?? null,
      }),
      REGISTRATION_TIMEOUT_MS,
      `Registration timed out after ${REGISTRATION_TIMEOUT_MS / 60000} minutes`
    );
  }

  if (provider === 'trae') {
    return await withTimeout(
      startTraeAutoreg({
        email,
        password: null,
        name: null,
        headless: config.advanced.headless,
        proxyUrl: config.proxy.enabled ? config.proxy.url : null,
        imapServer,
        imapPort: config.imap.port || DEFAULT_IMAP_PORT,
        imapUser,
        imapPassword,
        addyioEnabled: config.imap.addyioEnabled ?? null,
        addyioApiToken: config.imap.addyioApiToken ?? null,
        addyioDomain: config.imap.addyioDomain ?? null,
        addyioAliasFormat: config.imap.addyioAliasFormat ?? null,
        addyioAutoDelete: config.imap.addyioAutoDelete ?? null,
        thirtyThreeMailEnabled: config.imap.thirtyThreeMailEnabled ?? null,
        thirtyThreeMailUsername: config.imap.thirtyThreeMailUsername ?? null,
        thirtyThreeMailDomain: config.imap.thirtyThreeMailDomain ?? null,
        mailtmEnabled: config.imap.mailtmEnabled ?? null,
      }),
      REGISTRATION_TIMEOUT_MS,
      `Registration timed out after ${REGISTRATION_TIMEOUT_MS / 60000} minutes`
    );
  }

  if (provider === 'github') {
    const githubPassword = `Gh${Math.random().toString(36).substring(2, 10)}!1`;
    return await withTimeout(
      startGithubAutoreg({
        email,
        password: githubPassword,
        username: null,
        verificationCode: null,
        headless: config.advanced.headless,
        imapServer,
        imapUser,
        imapPassword,
      }),
      REGISTRATION_TIMEOUT_MS,
      `Registration timed out after ${REGISTRATION_TIMEOUT_MS / 60000} minutes`
    );
  }

  if (provider === 'openai') {
    const normalizedImapServer = imapServer?.trim() ? imapServer : null;
    const normalizedImapUser = imapUser?.trim() ? imapUser : null;
    const normalizedImapPassword =
      imapPassword?.trim() && imapPassword !== '********' ? imapPassword : null;

    return await withTimeout(
      startOpenAIAutoreg({
        email,
        password: null,
        name: null,
        headless: config.advanced.headless,
        proxyUrl: config.proxy.enabled ? config.proxy.url : null,
        imapServer: normalizedImapServer,
        imapPort: normalizedImapServer ? config.imap.port || DEFAULT_IMAP_PORT : null,
        imapUser: normalizedImapUser,
        imapPassword: normalizedImapPassword,
        addyioEnabled: config.imap.addyioEnabled ?? null,
        addyioApiToken: config.imap.addyioApiToken ?? null,
        addyioDomain: config.imap.addyioDomain ?? null,
        addyioAliasFormat: config.imap.addyioAliasFormat ?? null,
        addyioAutoDelete: config.imap.addyioAutoDelete ?? null,
        mailtmEnabled: config.imap.mailtmEnabled ?? null,
        thirtyThreeMailEnabled: config.imap.thirtyThreeMailEnabled ?? null,
        thirtyThreeMailUsername: config.imap.thirtyThreeMailUsername ?? null,
        thirtyThreeMailDomain: config.imap.thirtyThreeMailDomain ?? null,
        // When using alias strategies, no email is passed from frontend;
        // use IMAP identity email as base recipient for generator internals.
        emailStrategy: config.imap.mailtmEnabled
          ? 'mailtm'
          : config.imap.addyioEnabled
            ? 'addyio'
            : config.imap.thirtyThreeMailEnabled
              ? '33mail'
              : null,
        baseEmail: config.imap.email || imapUser || null,
      }),
      REGISTRATION_TIMEOUT_MS,
      `Registration timed out after ${REGISTRATION_TIMEOUT_MS / 60000} minutes`
    );
  }

  // Default: Kiro/AWS (Python autoreg)
  return await withTimeout(
    startPythonAutoreg({
      email,
      name: null,
      password: null,
      headless: config.advanced.headless,
      deviceFlow: false,
      autoGenerate: false,
      imapServer,
      imapPort: config.imap.port || DEFAULT_IMAP_PORT,
      imapUser,
      imapPassword,
      emailStrategy: null,
      proxyUrl: config.proxy.enabled ? config.proxy.url : null,
      speedMultiplier: config.advanced.speedMultiplier,
      verificationCodeTimeout: config.advanced.verificationCodeTimeout,
      oauthCallbackTimeout: config.advanced.oauthCallbackTimeout,
      allowAccessWait: config.advanced.allowAccessWait,
      pageLoadTimeout: config.advanced.pageLoadTimeout,
      elementWaitTimeout: config.advanced.elementWaitTimeout,
      imapPollInterval: config.advanced.imapPollInterval,
      passwordLength: config.advanced.passwordLength,
      realisticTyping: config.advanced.realisticTyping,
      humanDelays: config.advanced.humanDelays,
      screenshotsOnError: config.advanced.screenshotsOnError,
      addyioEnabled: config.imap.addyioEnabled ?? null,
      addyioApiToken: config.imap.addyioApiToken ?? null,
      addyioDomain: config.imap.addyioDomain ?? null,
      addyioAliasFormat: config.imap.addyioAliasFormat ?? null,
      addyioAutoDelete: config.imap.addyioAutoDelete ?? null,
      thirtyThreeMailEnabled: config.imap.thirtyThreeMailEnabled ?? null,
      thirtyThreeMailUsername: config.imap.thirtyThreeMailUsername ?? null,
      thirtyThreeMailDomain: config.imap.thirtyThreeMailDomain ?? null,
      mailtmEnabled: config.imap.mailtmEnabled ?? null,
    }),
    REGISTRATION_TIMEOUT_MS,
    `Registration timed out after ${REGISTRATION_TIMEOUT_MS / 60000} minutes`
  );
}

/**
 * Process registration result and save to database
 */
async function processRegistrationResult(params: {
  result: any;
  provider: ProviderName;
  index: number;
  totalCount: number;
  onLog: (level: LogLevel, message: string) => void;
  onHistoryEntry: (entry: {
    provider: ProviderName;
    email: string;
    status: RegistrationStatus;
  }) => void;
}): Promise<'success' | 'skip' | 'fail'> {
  const { result, provider, index, totalCount, onLog, onHistoryEntry } = params;

  // Check if registration succeeded based on provider-specific criteria
  const isWindsurf = provider === 'windsurf';
  const windsurfApiKey = isWindsurf ? (result.apiKey ?? result.api_key) : null;
  const hasRequiredData = isWindsurf
    ? result.success && result.email
    : result.success && result.email && result.password;

  if (hasRequiredData) {
    try {
      await addAccount({
        provider,
        email: result.email!,
        password: result.password || '',
        token: 'token' in result && result.token ? result.token : undefined,
        refreshToken:
          'refreshToken' in result && result.refreshToken ? result.refreshToken : undefined,
        metadata: 'name' in result && result.name ? { name: result.name } : undefined,
      });

      onLog('success', `[${index + 1}/${totalCount}] Account created: ${result.email}`);
      onHistoryEntry({
        provider,
        email: result.email!,
        status: 'completed',
      });
      return 'success';
    } catch (err) {
      const errMsg = String(err);
      if (errMsg.includes('already exists') || errMsg.includes('Duplicate')) {
        // Account exists but registration succeeded - count as success
        onLog(
          'success',
          `[${index + 1}/${totalCount}] Account ${result.email} updated (was already in database)`
        );
        onHistoryEntry({
          provider,
          email: result.email!,
          status: 'completed',
        });
        return 'success';
      } else {
        onLog('error', `[${index + 1}/${totalCount}] Failed to save account: ${errMsg}`);
        return 'fail';
      }
    }
  } else {
    // Registration failed
    const keys = result && typeof result === 'object' ? Object.keys(result).sort() : [];
    const json = (() => {
      try {
        return JSON.stringify(result);
      } catch {
        return null;
      }
    })();
    const jsonShort = json && json.length > 900 ? `${json.slice(0, 900)}...` : json;

    onLog(
      'error',
      `[${index + 1}/${totalCount}] Registration failed: ${result.error || 'Unknown error'}`
    );
    onLog(
      'error',
      `[${index + 1}/${totalCount}] Debug: provider=${provider}, success=${String(
        result?.success
      )}, email=${String(result?.email)}, error=${String(result?.error)}, apiKey=${
        windsurfApiKey ? 'present' : 'missing'
      }, keys=${keys.join(',')}`
    );
    if (jsonShort) {
      onLog('error', `[${index + 1}/${totalCount}] Debug JSON: ${jsonShort}`);
    }
    return 'fail';
  }
}

/**
 * Wrap promise with timeout
 */
function withTimeout<T>(promise: Promise<T>, timeoutMs: number, errorMessage: string): Promise<T> {
  return Promise.race([
    promise,
    new Promise<T>((_, reject) => setTimeout(() => reject(new Error(errorMessage)), timeoutMs)),
  ]);
}

/**
 * Delay helper
 */
function delay(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms));
}
