export interface IdentityTranslations {
  identity: {
    activeLabel: string;
    autoGeneratedAddresses: string;
    imapOk: string;
    mailtmDescription: string;
    noImapConfigNeeded: string;
    perfectForOneTimeRegistrations: string;
    planLabel: string;
    temporaryEmailService: string;
  };
}
