import {
  listAccounts,
  stopRegistration,
  setAccountProxy,
} from '../../../../lib/backend';
import { generateEmail } from '../emailGenerator';
import type { ProviderName } from '../../../../types/ui';
import { validateAliasConfiguration } from '../aliasValidation';
import type {
  LogLevel,
  RegistrationOptions,
  RegistrationProcessResult,
  RegistrationStatus,
  RegistrationSummary,
} from './types';
import { getIMAPCredentials, runProviderRegistration, runRegistrationV2 } from './steps';
import { cancelActiveRegistrationJob, delay } from './recovery';

/**
 * Run registration for multiple accounts
 */
export async function runRegistration(options: RegistrationOptions): Promise<RegistrationSummary> {
  const { config, emailDomain, useRegistrationV2, onLog, onHistoryEntry, onCancelled } = options;

  const totalCount = config.count || 1;
  let successCount = 0;
  let skipCount = 0;
  let failCount = 0;

  // Determine IMAP credentials based on strategy (once, outside loop)
  const { imapServer, imapUser, imapPassword } = getIMAPCredentials(config);

  // Debug log IMAP config (without password)
  onLog(
    'debug',
    `IMAP config: server=${imapServer}, user=${imapUser}, password=${imapPassword ? '***set***' : '***empty***'}`
  );

  try {
    // Loop for multiple account registration
    for (let i = 0; i < totalCount; i++) {
      // Check if cancelled
      if (onCancelled()) {
        onLog('warn', `Registration cancelled by user at account ${i + 1}/${totalCount}`);
        break;
      }

      try {
        // Use Registration V2 for AWS/Kiro if enabled
        if (useRegistrationV2 && config.provider === 'aws') {
          const result = await runRegistrationV2(i, totalCount, onLog);
          if (result.success && result.email) {
            successCount++;
            onLog('success', `[${i + 1}/${totalCount}] Account created: ${result.email}`);
            onHistoryEntry({
              provider: config.provider,
              email: result.email,
              status: 'completed',
            });
          } else {
            failCount++;
            onLog(
              'error',
              `[${i + 1}/${totalCount}] Registration failed: ${result.error || 'Unknown error'}`
            );
          }

          // Delay between registrations
          if (i < totalCount - 1) {
            await delay(config.advanced.delayBetweenAccounts * 1000);
          }
          continue;
        }

        // Generate email
        const emailResult = await generateEmail({
          provider: config.provider,
          imapConfig: config.imap,
          emailPattern: config.patterns.emailPattern,
          emailCustomPrefix: config.patterns.emailCustomPrefix,
          emailDomain,
        });

        const { email, strategy, shouldGenerateInPython } = emailResult;

        if (shouldGenerateInPython) {
          const aliasValidationError = validateAliasConfiguration(strategy, config);
          if (aliasValidationError) {
            failCount++;
            onLog('error', `[${i + 1}/${totalCount}] ${aliasValidationError}`);
            continue;
          }
        }

        const profileLaunchMode = options.launchContext?.source === 'profile';

        if (profileLaunchMode) {
          onLog(
            'info',
            `[${i + 1}/${totalCount}] Using standalone profile: ${options.launchContext?.profileAlias}`
          );
        }

        if (shouldGenerateInPython) {
          const serviceName =
            strategy === 'addyio'
              ? 'addy.io'
              : strategy === '33mail'
                ? '33mail'
                : strategy === 'icloud_pool'
                  ? 'iCloud Hide My Email'
                  : 'Mail.tm';
          onLog('info', `[${i + 1}/${totalCount}] Using ${serviceName} for email generation...`);
        }

        // Check if account already exists (skip if email will be generated by Python)
        if (email && !profileLaunchMode) {
          const existingAccounts = await listAccounts({ provider: config.provider });
          const accountExists = existingAccounts.some(
            acc => acc.email.toLowerCase() === email.toLowerCase()
          );

          if (accountExists) {
            skipCount++;
            onLog(
              'warn',
              `[${i + 1}/${totalCount}] Account ${email} already exists in database, skipping`
            );
            continue;
          }
        }

        onLog(
          'info',
          `[${i + 1}/${totalCount}] Registering ${email || '(email will be generated)'}...`
        );

        // Run provider-specific registration
        const result = await runProviderRegistration({
          provider: config.provider,
          email,
          aliasStrategy: shouldGenerateInPython ? strategy : null,
          config,
          imapServer,
          imapUser,
          imapPassword,
          onCancelled,
          onLog,
          launchContext: options.launchContext,
          pipelineStepOverrides: options.pipelineStepOverrides,
        });

        // Process result
        const processResult = await processRegistrationResult({
          result,
          provider: config.provider,
          index: i,
          totalCount,
          onLog,
          onHistoryEntry,
          proxyLibraryId: config.proxy.enabled ? config.proxy.proxyLibraryId : undefined,
        });

        if (processResult === 'success') {
          successCount++;
        } else if (processResult === 'skip') {
          skipCount++;
        } else {
          failCount++;
        }

        // Delay between registrations
        if (i < totalCount - 1) {
          onLog(
            'debug',
            `Waiting ${config.advanced.delayBetweenAccounts}s before next registration...`
          );
          await delay(config.advanced.delayBetweenAccounts * 1000);
        }
      } catch (error) {
        const errorMsg = String(error);

        if (onCancelled() || /cancelled/i.test(errorMsg)) {
          onLog('warn', `[${i + 1}/${totalCount}] Registration cancelled`);
          break;
        }

        failCount++;

        if (errorMsg.includes('timed out')) {
          onLog(
            'error',
            `[${i + 1}/${totalCount}] ${errorMsg} - attempting to stop process and continue...`
          );
          // Try to stop the hung process
          try {
            await cancelActiveRegistrationJob();
            await stopRegistration();
          } catch {
            // Ignore stop errors
          }
        } else {
          onLog('error', `[${i + 1}/${totalCount}] Error: ${errorMsg}`);
        }
      }

      // Log progress after each iteration
      onLog(
        'debug',
        `Completed ${i + 1}/${totalCount} registrations (success: ${successCount}, skip: ${skipCount}, fail: ${failCount})`
      );
    }
  } catch (error) {
    onLog('error', `Fatal error: ${String(error)}`);
    throw error;
  }

  return { successCount, skipCount, failCount };
}

/**
 * Process registration result and save to database
 */
async function processRegistrationResult(params: {
  result: RegistrationProcessResult;
  provider: ProviderName;
  index: number;
  totalCount: number;
  onLog: (level: LogLevel, message: string) => void;
  onHistoryEntry: (entry: {
    provider: ProviderName;
    email: string;
    status: RegistrationStatus;
  }) => void;
  proxyLibraryId?: string | null;
}): Promise<'success' | 'skip' | 'fail'> {
  const { result, provider, index, totalCount, onLog, onHistoryEntry, proxyLibraryId } = params;

  // Account persistence is backend-owned (Rust emits ACCOUNT_ADDED); runner only records history
  const hasRequiredData = result?.success && result?.email;
  const windsurfApiKey = provider === 'windsurf' ? (result.apiKey ?? result.api_key) : null;

  if (hasRequiredData) {
    onLog('success', `[${index + 1}/${totalCount}] Registration succeeded: ${result.email}`);
    onHistoryEntry({
      provider,
      email: result.email as string,
      status: 'completed',
    });

    // Bind proxy to newly created account (best-effort)
    if (proxyLibraryId && result.email) {
      try {
        const accounts = await listAccounts({ provider });
        const newAccount = accounts.find(
          (a) => a.email.toLowerCase() === (result.email as string).toLowerCase()
        );
        if (newAccount) {
          await setAccountProxy({ accountId: newAccount.id, proxyId: proxyLibraryId });
          onLog('debug', `Proxy bound to account ${newAccount.id}`);
        }
      } catch {
        // Non-critical — proxy binding failure shouldn't fail registration
      }
    }

    return 'success';
  } else {
    // Registration failed
    const keys = result && typeof result === 'object' ? Object.keys(result).sort() : [];
    const json = (() => {
      try {
        return JSON.stringify(result);
      } catch {
        return null;
      }
    })();
    const jsonShort = json && json.length > 900 ? `${json.slice(0, 900)}...` : json;

    onLog(
      'error',
      `[${index + 1}/${totalCount}] Registration failed: ${result.error || 'Unknown error'}`
    );
    onLog(
      'error',
      `[${index + 1}/${totalCount}] Debug: provider=${provider}, success=${String(
        result?.success
      )}, email=${String(result?.email)}, error=${String(result?.error)}, apiKey=${windsurfApiKey ? 'present' : 'missing'
      }, keys=${keys.join(',')}`
    );
    if (jsonShort) {
      onLog('error', `[${index + 1}/${totalCount}] Debug JSON: ${jsonShort}`);
    }
    return 'fail';
  }
}
