#!/usr/bin/env python3
"""Generate stitch_backend/version.py from git tag or package.json.

Usage:
    python scripts/generate_version.py           # from package.json version
    python scripts/generate_version.py 1.2.3     # explicit version (CI release)
"""

from __future__ import annotations

import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_FILE = REPO_ROOT / "python" / "stitch_backend" / "version.py"

TEMPLATE = '''"""Application version. GENERATED by scripts/generate_version.py — do not edit."""

__version__ = "{version}"
__build_date__ = "{build_date}"
__git_commit__ = "{git_commit}"
'''


def get_git_commit() -> str:
    import subprocess
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, cwd=REPO_ROOT, timeout=10,
        )
        return result.stdout.strip() if result.returncode == 0 else "unknown"
    except Exception:
        return "unknown"


def main() -> int:
    if len(sys.argv) > 1:
        version = sys.argv[1].lstrip("v")
    else:
        pkg = json.loads((REPO_ROOT / "package.json").read_text(encoding="utf-8"))
        version = pkg.get("version", "0.0.0")

    if not re.match(r"^\d+\.\d+\.\d+", version):
        print(f"ERROR: invalid version '{version}'", file=sys.stderr)
        return 1

    OUT_FILE.write_text(
        TEMPLATE.format(
            version=version,
            build_date=datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            git_commit=get_git_commit(),
        ),
        encoding="utf-8",
    )
    print(f"Generated {OUT_FILE.relative_to(REPO_ROOT)}: v{version}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
